### ISSUE TITLE
Servlet 3.0 Features not supported

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/appengine-java-vm-guestbook-extras#10]
Customer is using Java with a VM engine and following instructions available at https://github.com/GoogleCloudPlatform/appengine-java-vm-guestbook-extras/blob/master/README.md.

Those instructions seem to indicate that the Servlet 3.1 API can be used on App Engine but I believe the Java runtime is currently on Servlet 2.5.

**Comment by ludoch** [comment]
No, Java Managed VMs support Servlet 3.1. This readme is correct.
