### ISSUE TITLE
gcloud needs better error reporting

### ISSUE THREAD

**Issue by apennebaker-ni** [GoogleCloudPlatform/appengine-java-vm-guestbook-extras#13]
The Maven gcloud plugin needs better error reporting. No matter how I configure my software stack, mvn gcloud:run reports:

INFO: Successfully processed /Users/apennebaker/Desktop/src/users-ws/users-impl/target/users-impl-1.22.0-SNAPSHOT/WEB-INF/appengine-web.xml
[ERROR] Error: gcloud app xxx exit code is: 1

mvn -X doesn't give any more detail.

**Comment by tmatsuo** [comment]
Thanks! Can you file the issue on:
https://github.com/GoogleCloudPlatform/gcloud-maven-plugin/issues
?

**Comment by apennebaker-ni** [comment]
Thanks for the tip, done!
