### ISSUE TITLE
Dockerfile publicly exposed 

### ISSUE THREAD

**Issue by newjam** [GoogleCloudPlatform/appengine-java-vm-guestbook-extras#14]
Since the Dockerfile is placed in src/main/webapp/Dockerfile it is publicly available over http. I imagine this was done to simplify the build process, but it seems like a security issue to me.

**Comment by ludoch** [comment]
You can use a dockerignore to configure what will be in the image.

See https://docs.docker.com/reference/builder/#dockerignore-file
